### ISSUE TITLE
[Docs] Showing how to use private git repos to host pub packages

### ISSUE THREAD

**Issue by raveesh-me** [dart-lang/site-www#1310]
In reference to:
https://github.com/dart-lang/pub/issues/1381#issuecomment-452610742

```
dependencies:
  kittens:
    git:
      url: git://github.com/munificent/kittens.git
      ref: some-branch
```
This is how we add a dependency from a github/gitlab repo
How we do it when the repo is private? Based on the thread this is possible but can we have updated doccumentation for the same?

https://www.dartlang.org/tools/pub/dependencies#git-packages
