### ISSUE TITLE
Analysis options doc is incorrect

### ISSUE THREAD

**Issue by nex3** [dart-lang/site-www#161]
[This documentation](https://www.dartlang.org/guides/language/analysis-options) for the analysis options file indicates that the `strong-mode` configuration options are a list:

```yaml
analyzer:
  strong-mode:
    - implicit-downcasts: false
    - implicit-dynamic: false
```

In fact, this won't work (see dart-lang/sdk#27622), and will disable strong mode even when `--strong` is passed. The correct format should pass the options as a map:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

Note that the initial `- `s are gone and `implicit-downcasts` is replaced with `implicit-casts`.
