### ISSUE TITLE
Pubspec includes two dependency overrides pointed at external repos

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/site-www#1757]
The site's pubspec:

https://github.com/dart-lang/site-www/blob/master/pubspec.yaml

Includes two dependency overrides that point to @chalin's personal GitHub account:

```yaml
dependency_overrides:
  code_excerpt_updater:
    git: https://github.com/chalin/code_excerpt_updater.git
    # path: ../code_excerpt_updater
  code_excerpter:
    git: https://github.com/chalin/code_excerpter.git
    # path: ../code_excerpter
```

While the repos are unlikely to be taken down, it'd be good to remove those overrides or point them to copies in a more official location.
