### ISSUE TITLE
document plugins in analysis_options.yaml

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/site-www#2013]
Now that David is working on another plugin, we should document how they work on the dart site to avoid confusion.

It can look like:

```yaml
analyzer:
  plugins:
    - my_package
```

or

```yaml
analyzer:
  plugins:
    my_package:
      my_custom: options
```

where my_package exports an analysis plugin.

For someone who wants to do _create a plugin_, we should probably ask them to file an issue so that we can advise them and/or approve their use case etc. @bwilkerson  does that sound good to you?

Otherwise, we could maybe just link to a plugin that exists as an example, such as the angular plugin, and not really make it look like something someone can "just write" since it is pretty nontrivial and that API is still subject to change.

For instance, the angular plugin looks like:

```yaml
analyzer:
  plugins:
    angular:
      enabled: true
      custom-tag-names:
        - foo
        - bar
      custom-events:
        foo:
          type: Foo
          path: 'package:bar/baz.dart'
```

but the `enabled: true` is something I added more or less on accident and I should remove the need for.

This is why it'd be good to document centrally -- rather than having others' go off of my code which may contain mistakes for backwards compatibility purposes.
