### ISSUE TITLE
'Get the Dart SDK' page issue

### ISSUE THREAD

**Issue by Y24** [dart-lang/site-www#2054]
Page URL: https://dart.dev/get-dart.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/get-dart.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
Well, the firefox seems to be hard to deal with while the same page in Chrome is OK.
![Screenshot from 2019-10-30 22-44-47](https://user-images.githubusercontent.com/37091129/67869499-7df6af00-fb68-11e9-8162-952b57f02547.png)

**Comment by kwalrath** [comment]
Oh, interesting. This is an issue only for the Linux tab, and only (afaik) in Firefox. Thank you for reporting it, @Y24!

**Comment by refi64** [comment]
Okay so I could reproduce this in Chrome 78 and decided to give it a look.

It's due to [this style rule](https://github.com/dart-lang/site-www/blob/3826ffbae424e426b8f99eac1e04630d7743261c/src/_assets/css/main.scss#L795):

```scss
  // Invisible pre-element to avoid modifying styles on headings.
  a[id]::before {
    @include header-clearance;
    content: "";
    display: block;
  }
```

Deleting the bullet point list's `::before` child fixes the issue in Chrome *and* Firefox. This appears to have been added during the big site redesign commit, though removing it altogether (by dropping the `content: ""`) doesn't really seem to affect anything?
