### ISSUE TITLE
Git URL in dependencies examples are not working

### ISSUE THREAD

**Issue by lzhuor** [dart-lang/site-www#2427]
Example given is using `git://` which causes error during `pub get` command:

```yaml
dependencies:
  kittens:
    git:
      url: git://github.com/munificent/kittens.git
      ref: some-branch
```

![image](https://user-images.githubusercontent.com/14172220/82437597-429edc00-9aca-11ea-8848-4e2642dc4b39.png)

The correct one should be `git@git@github.com/XXX`

**Comment by kwalrath** [comment]
Thanks for the issue & PR, @lzhuor! I've asked an engineer to review the PR.

**Comment by jonasfj** [comment]
I have no problems cloning:
```yaml
name: hack
dependencies:
        retry:
                git:
                        url: git://github.com/google/dart-neats.git
                        ref: master
                        path: retry
```

On linux in a  clean docker image without any special configuration of my git client.

-----------
That said, it might be fine to improve the documentation by pointing out that any url that works with `git clone <url>` will do. And that the common forms for this on github is:
 * `git@github.com:munificent/kittens.git` for private repositories, and,
 * `https://github.com/munificent/kittens.git` for public repositories.
