### ISSUE TITLE
Document Git path dependencies

### ISSUE THREAD

**Issue by nex3** [dart-lang/site-www#314]
In dart-lang/pub#1650, pub adds support for depending on subdirectories of Git repositories. The syntax for this is:

```yaml
dependencies:
  foobar:
    git:
      url: git://github.com/dart-lang/multi_package_repo
      path: pkg/foobar
```

This will depend on the package defined by `pkg/foobar/pubspec.yaml` in the `multi_package_repo` repository.
