### ISSUE TITLE
Don't unnecessarily specify border-width twice for blockquotes

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3617]
### Describe the problem

In [main.css](https://github.com/dart-lang/site-www/blob/master/src/_assets/css/main.scss#L1393-L1394) we specify the border style for `blockquote`s but then overwrite the border-width we just set. 

### Expected fix

We can just not set the border-width in the `border` shorthand property to simplify it to:

```css
blockquote {
  border: solid #b3b3b3;
  border-width: 1px 0;
  margin: 20px;
  padding: 10px 20px 0 20px;
}
```
