### ISSUE TITLE
Show path dependencies for git packages

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#408]
In https://www.dartlang.org/tools/pub/dependencies#git-packages, add an example like this:

```
angular:
  git:
    url: git@github.com:dart-lang/angular.git
    path: angular
```
