### ISSUE TITLE
'Dart 2.0 Updates' should be more clear about SDK constraints on dev SDKs

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#487]
From URL: https://www.dartlang.org/dart-2.0#upper-constraints-on-the-sdk-version

We should add some notes to this block

```yaml
sdk: '>=1.20.1 <2.0.0'
sdk: '>=2.0.0-dev.1.2 <2.0.0'
```

See the block at the end of this article: https://news.dartlang.org/2017/09/dart-20-pre-releases-what-they-mean-to.html

```yaml
# Works in 1.20.1+; might work in 2.0.0-dev:
sdk: '>=1.20.1 <2.0.0'       

# Backward incompatible change requires at least 2.0.0-dev.1.2:
sdk: '>=2.0.0-dev.1.2 <2.0.0'
```
