### ISSUE TITLE
Change dependabot labeling to accommodate new labeling system

### ISSUE THREAD

**Issue by atsansone** [dart-lang/site-www#5084]
### Describe the problem

This adjusts automatic updates to scoped labels and the dependabot.yaml file adjust to work in that manner. 

Per https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#setting-custom-labels

### Expected fix

In .github/dependabot.yml, change

```yaml
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - autosubmit
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'daily'
```

to 

```yaml
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "infra.dependencies"
      - "infra.bundler"
      - "lang.ruby"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "infra.dependencies"
      - "infra.docker"
      - "lang.yaml"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "infra.dependencies"
      - "infra.github-action"
      - "lang.yaml"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    labels:
      - "infra.dependencies"
      - "infra.npm"
      - "lang.javascript"
  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - "infra.dependencies"
      - "infra.submodules"
```
