### ISSUE TITLE
Disallow search engines on every host other than www.dartlang.org

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#748]
See https://www.google.com/search?q=site:dartlang-org-staging-0.firebaseapp.com

We don't want search engines wasting time with our dev domains.

We set this up with the package site. See https://dartlang-pub.appspot.com/robots.txt

Could we figure this out w/ our deploy script(s)?

**Comment by bcko** [comment]
[.travis.yml](https://github.com/dart-lang/site-webdev/blob/master/.travis.yml), deploy for `master` and `5-dev` branch are currently set as `--robots-ok`. below is the part from .travis.yml

```
 deploy:
        - provider: script
          script: ./scripts/deploy/firebase.sh --robots-ok dev
          skip_cleanup: true
          on:
            repo: dart-lang/site-webdev
            branch: master
            condition: $CI_TASK == build*
        - provider: script
          script: ./scripts/deploy/firebase.sh --robots-ok dev
          skip_cleanup: true
          on:
            repo: dart-lang/site-webdev
            branch: 5-dev
            condition: $CI_TASK == build*
```
Omitting `--robots-ok` disallows search engines from crawling. 
What would be the best way to resolve this issue? would omitting `--robots-ok` and redeploy to Firebase work? Thank you
